### ISSUE TITLE
Week13 is ready for grading!

### ISSUE THREAD

**Issue by nmlund-matc** [madisoncollege-it-programs/python-scripting-nmlund-matc#13]

**Comment by cethenmc** [comment]
Hi, Nick.  You are almost there.  I will give you a 6 of 8 for now.

line 13 should probably not use x.  What else could you use?
line 14 is unnecessarily casting to a string, and since it is not a formatted string for printing, I should not see curly brackets

Suppose you opened your copied web page from a browser.  You would know that it does not look like the web page.

Full credit for the inspect-web.py portion of the assignment.  The directions were not very clear in that when it was asking to get every link, it also wanted the href.  With the rules being unclear, I accept the link name you provide.  I would also take just the links.  In an ideal world, I would see both.  If you would like to add to your own, change your print(link.get_text('href')) statement to:

print(f"{link.text}:  {link.get('href')}")

**Comment by nmlund-matc** [comment]
Made corrections to this and removed brackets and changed X to an A

**Comment by cethenmc** [comment]
Nice work.  Full credit!  8 out of 8.
