### ISSUE TITLE
Week 2 - Assignment 2 is ready for grading!

### ISSUE THREAD

**Issue by nmlund-matc** [madisoncollege-it-programs/python-scripting-nmlund-matc#2]
No questions so far in the class, but you are making this class easy and enjoyable to learn!

**Comment by cethenmc** [comment]
Hi, Nick.  Did you try to execute this script from the command line?  It has errors.  Can you figure out why?  Please reply to this issue when the script has become error free.  ~Chris

**Comment by cethenmc** [comment]
Hi Nick.  You had not replied to this saying week2, assignment 2 is ready.  However, since it has been so long, I thought I would check anyway.   You are getting errors.  Do you need a hand?  Try moving the shebang line to the top of the script.

. (first-script . py: line 5: my_name: command not found 
. (first-script . py: line 6: syntax error near unexpected token 'f"My name is {my_name} , and something I have learned in this class so far is that everything is an object in Python!")' 
. (first-script . py. line 6: print (f"My name is {my_name}, and something I have learned in this class so far is that everything is an object in Python! ")' 

Please knock this out today if you can!

Thanks.

~Chris

**Comment by cethenmc** [comment]
Thanks for pushing it after class.  It is now graded.
